#define COMMA                            1
#define EQ                               2
#define BR1                              3
#define BR2                              4
#define INTTYPE                          5
#define STRTYPE                          6
#define COLORARRTYPE                     7
#define INTARRTYPE                       8
#define RECTTYPE                         9
#define COLVAL                          10
#define INTVAL                          11
#define STRVAL                          12
