/* Generated by re2c 0.13.7.5 on Thu Aug 27 21:45:24 2015 */

#include "stdafx.h"

typedef unsigned char uchar;
typedef unsigned int uint;

#define	YYCTYPE		uchar
#define	YYCURSOR	cursor
#define	YYLIMIT		s->lim
#define	YYMARKER	s->ptr

#define	RET(i)	{s->cur = cursor; return i;}
#define	RETT(i, typeid)	{s->cur = cursor; s->val.type = typeid; return i;}

typedef struct PassData
{
  union {
      int i;
      CString *str;
      COLORREF col;
  };
  uint		type;
} PassData;

typedef struct Scanner
{
    int			fd;
    uchar		*bot, *tok, *ptr, *cur, *pos, *lim, *top, *eof;
    uint		line;
    PassData val;
} Scanner;

enum {TYPE_CharSet=0, TYPE_AutoDetect, TYPE_ByteOrder, TYPE_FontName, TYPE_FontStyle, TYPE_FontSize, TYPE_FrameLeft, TYPE_FrameTop, TYPE_CmdShow, TYPE_FrameHeight, TYPE_FrameHeight2, TYPE_FrameWidth2, TYPE_SplitHPos, TYPE_SplitVPos, TYPE_SplitStruct, TYPE_StructView, TYPE_ComboHeight, TYPE_Language, TYPE_DetectMax, TYPE_BarState, TYPE_ReadOnly, TYPE_BmpWidth, TYPE_BmpZoom, TYPE_BmpPallet, TYPE_MaxOnMemory, TYPE_MaxMapSize, TYPE_TagAll, TYPE_SubCursor, TYPE_Colors, TYPE_MemberColumns2, TYPE_PageMargin, TYPE_DumpHeader, TYPE_DumpPage, TYPE_QWordAddr, TYPE_ClearUndoRedoWhenSave, TYPE_SyncScroll, TYPE_Grid, TYPE_BmpColorWidth, TYPE_InspectView, TYPE_AnalyzerView, TYPE_BmpAddressTooltip};

void SetIntOption(uint type, int val)
{
  switch(type)
  {
case TYPE_CharSet: options.charset = (CharSet)val; break;
case TYPE_AutoDetect: options.bAutoDetect = val; break;
case TYPE_ByteOrder: options.bByteOrder = val; break;
case TYPE_FontStyle: options.fFontStyle = val; break;
case TYPE_FontSize: options.nFontSize = val; break;
case TYPE_FrameLeft: options.ptFrame.x = val; break;
case TYPE_FrameTop: options.ptFrame.y = val; break;
case TYPE_CmdShow: options.nCmdShow = val; break;
case TYPE_FrameHeight: options.cyFrame = val; break;
case TYPE_FrameHeight2: options.cyFrame2 = val; break;
case TYPE_FrameWidth2: options.cxFrame2 = val; break;
case TYPE_SplitHPos: options.xSplit = val; break;
case TYPE_SplitVPos: options.ySplit = val; break;
case TYPE_SplitStruct: options.xSplitStruct = val; break;
case TYPE_StructView: options.bStructView = val; break;
case TYPE_ComboHeight: options.nComboHeight = val; break;
case TYPE_Language: options.bLanguage = val; break;
case TYPE_DetectMax: options.dwDetectMax = val; break;
case TYPE_BarState: options.barState = val; break;
case TYPE_ReadOnly: options.bReadOnlyOpen = val; break;
case TYPE_BmpWidth: options.nBmpWidth = val; break;
case TYPE_BmpZoom: options.nBmpZoom = val; break;
case TYPE_BmpPallet: options.nBmpPallet = val; break;
case TYPE_MaxOnMemory: options.dwMaxOnMemory = val; break;
case TYPE_MaxMapSize: options.dwMaxMapSize = val; break;
case TYPE_TagAll: options.bTagAll = val; break;
case TYPE_SubCursor: options.bSubCursor = val; break;
case TYPE_DumpPage: options.nDumpPage = val; break;
case TYPE_QWordAddr: options.bQWordAddr = val; break;
case TYPE_ClearUndoRedoWhenSave: options.bClearUndoRedoWhenSave = val; break;
case TYPE_SyncScroll: options.bSyncScroll = val; break;
case TYPE_Grid: options.iGrid = val; break;
case TYPE_BmpColorWidth: options.nBmpColorWidth = val; break;
case TYPE_InspectView: options.bInspectView = val; break;
case TYPE_AnalyzerView: options.bAnalyzerView = val; break;
case TYPE_BmpAddressTooltip: options.bAddressTooltip = val; break;
	}
}

void SetStrOption(uint type, CString *pVal)
{
  switch(type)
  {
case TYPE_FontName: options.sFontName = *pVal; break;
case TYPE_DumpHeader: options.sDumpHeader = *pVal; break;
	}
}

void SetColorArrOption(uint type, CAtlArray<COLORREF> *pVal)
{
  switch(type)
  {
		case TYPE_Colors:
		{
			COLORREF *col = &(options.colors[0][0]);
			for(int i=0;i < TCOLOR_COUNT*2 && i < pVal->GetCount();i++)
			{
			  col[i] = (*pVal)[i];
			}
			break;
		}
	}
}

void SetIntArrOption(uint type, CAtlArray<int> *pVal)
{
  switch(type)
  {
		case TYPE_MemberColumns2:
		{
			for(int i=0;i < MBRCOL2_MAX && i < pVal->GetCount();i++)
			{
			  options.colWidth2[i] = (*pVal)[i];
			}
			break;
		}
	}
}

void SetRectOption(uint type, int *pVal)
{
  switch(type)
  {
case TYPE_PageMargin: options.rMargin.left = pVal[0]; options.rMargin.top = pVal[1]; options.rMargin.right = pVal[2]; options.rMargin.bottom = pVal[3]; break;
	}
}

#include "PortableCfgParser.h"
#include "PortableCfgParser.c"


COLORREF ReadRGB(uchar *token)
{
  COLORREF c=0xFF000000;
  _snscanf((const char *)token, 6, "%06x", &c);
  return c;
}

COLORREF ReadRGBA(uchar *token)
{
  COLORREF c=0;
  _snscanf((const char *)token, 8, "%08x", &c);
  return c;
}

CString ReadStr(uchar *token, uint len)
{
  CStringA tmpA;
  tmpA.SetString((const char *)token, len);
  CStringW tmpB = CA2W(tmpA, CP_UTF8);
  tmpB.Replace(L"%", L"%%");
  CString retStr;
  retStr.Format(tmpB);
  return retStr;
}

BOOL fill(int n) { return FALSE; }

int scan(Scanner *s){
	uchar *cursor = s->cur;
std:
	s->tok = cursor;



{
	YYCTYPE yych;
	unsigned int yyaccept = 0;

	if ((YYLIMIT - YYCURSOR) < 21) if(!fill(21)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy19;
	case '\n':	goto yy36;
	case '\v':
	case '\f':	goto yy35;
	case 0x1A:	goto yy33;
	case '"':	goto yy24;
	case '#':	goto yy23;
	case '+':
	case '-':	goto yy18;
	case ',':	goto yy31;
	case '/':	goto yy2;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy21;
	case '=':	goto yy25;
	case 'A':	goto yy5;
	case 'B':	goto yy6;
	case 'C':	goto yy4;
	case 'D':	goto yy10;
	case 'F':	goto yy7;
	case 'G':	goto yy16;
	case 'I':	goto yy17;
	case 'L':	goto yy9;
	case 'M':	goto yy12;
	case 'P':	goto yy14;
	case 'Q':	goto yy15;
	case 'R':	goto yy11;
	case 'S':	goto yy8;
	case 'T':	goto yy13;
	case '{':	goto yy27;
	case '}':	goto yy29;
	default:	goto yy38;
	}
yy2:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '*':	goto yy416;
	case '/':	goto yy414;
	default:	goto yy3;
	}
yy3:
	{
    ATLTRACE("unexpected character: %c\n", *s->tok);
    goto std;
  }
yy4:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'h':	goto yy366;
	case 'l':	goto yy363;
	case 'm':	goto yy365;
	case 'o':	goto yy364;
	default:	goto yy3;
	}
yy5:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'n':	goto yy341;
	case 'u':	goto yy342;
	default:	goto yy3;
	}
yy6:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy279;
	case 'm':	goto yy278;
	case 'y':	goto yy280;
	default:	goto yy3;
	}
yy7:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'o':	goto yy232;
	case 'r':	goto yy231;
	default:	goto yy3;
	}
yy8:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'p':	goto yy184;
	case 't':	goto yy183;
	case 'u':	goto yy182;
	case 'y':	goto yy181;
	default:	goto yy3;
	}
yy9:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy173;
	default:	goto yy3;
	}
yy10:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'e':	goto yy150;
	case 'u':	goto yy149;
	default:	goto yy3;
	}
yy11:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'e':	goto yy141;
	default:	goto yy3;
	}
yy12:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy109;
	case 'e':	goto yy108;
	default:	goto yy3;
	}
yy13:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy102;
	default:	goto yy3;
	}
yy14:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'a':	goto yy92;
	default:	goto yy3;
	}
yy15:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'W':	goto yy83;
	default:	goto yy3;
	}
yy16:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'r':	goto yy79;
	default:	goto yy3;
	}
yy17:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case 'n':	goto yy68;
	default:	goto yy3;
	}
yy18:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\t':
	case ' ':	goto yy66;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy62;
	default:	goto yy3;
	}
yy19:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy65;
yy20:
	{ if(cursor == s->eof)RET(0); goto std; }
yy21:
	++YYCURSOR;
	yych = *YYCURSOR;
	goto yy63;
yy22:
	{ uchar *start = s->tok;
				bool bMinus = false;
				if(*start == '-')bMinus = true;
				while(*start<'0' || *start>'9')start++;
				CStringA tmp;
				tmp.SetString((const char *)(start), cursor - start);
				s->val.i = bMinus ? -atoi(tmp) : atoi(tmp);
				RET(INTVAL); }
yy23:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy52;
	default:	goto yy3;
	}
yy24:
	yyaccept = 0;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '\n':	goto yy3;
	default:	goto yy42;
	}
yy25:
	++YYCURSOR;
	{ RET(EQ); }
yy27:
	++YYCURSOR;
	{ RET(BR1); }
yy29:
	++YYCURSOR;
	{ RET(BR2); }
yy31:
	++YYCURSOR;
	{ RET(COMMA); }
yy33:
	++YYCURSOR;
	{ RET(0);/*EOF*/ }
yy35:
	yych = *++YYCURSOR;
	goto yy40;
yy36:
	++YYCURSOR;
	{
    if(cursor == s->eof)RET(0);
    s->pos = cursor; s->line++;
    goto std;
  }
yy38:
	yych = *++YYCURSOR;
	goto yy3;
yy39:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
yy40:
	switch (yych) {
	case '\t':
	case '\v':
	case '\f':
	case ' ':	goto yy39;
	default:	goto yy20;
	}
yy41:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
yy42:
	switch (yych) {
	case '\n':	goto yy43;
	case '"':	goto yy45;
	case '\\':	goto yy44;
	default:	goto yy41;
	}
yy43:
	YYCURSOR = YYMARKER;
	if (yyaccept == 0) {
		goto yy3;
	} else {
		goto yy58;
	}
yy44:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '"':
	case '\'':
	case '?':
	case '\\':
	case 'a':
	case 'b':
	case 'f':
	case 'n':
	case 'r':
	case 't':
	case 'v':	goto yy41;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy48;
	case 'x':	goto yy47;
	default:	goto yy43;
	}
yy45:
	++YYCURSOR;
	{ s->val.str = new CString(); *(s->val.str) = ReadStr(s->tok + 1, cursor - s->tok -2); RET(STRVAL); }
yy47:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy50;
	default:	goto yy43;
	}
yy48:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy43;
	case '"':	goto yy45;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':	goto yy48;
	case '\\':	goto yy44;
	default:	goto yy41;
	}
yy50:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy43;
	case '"':	goto yy45;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy50;
	case '\\':	goto yy44;
	default:	goto yy41;
	}
yy52:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy53;
	default:	goto yy43;
	}
yy53:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy54;
	default:	goto yy43;
	}
yy54:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy55;
	default:	goto yy43;
	}
yy55:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy56;
	default:	goto yy43;
	}
yy56:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy57;
	default:	goto yy43;
	}
yy57:
	yyaccept = 1;
	yych = *(YYMARKER = ++YYCURSOR);
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy59;
	default:	goto yy58;
	}
yy58:
	{ s->val.col = ReadRGB(s->tok + 1); RET(COLVAL); }
yy59:
	yych = *++YYCURSOR;
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':
	case 'A':
	case 'B':
	case 'C':
	case 'D':
	case 'E':
	case 'F':
	case 'a':
	case 'b':
	case 'c':
	case 'd':
	case 'e':
	case 'f':	goto yy60;
	default:	goto yy43;
	}
yy60:
	++YYCURSOR;
	{ s->val.col = ReadRGBA(s->tok + 1); RET(COLVAL); }
yy62:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
yy63:
	switch (yych) {
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy62;
	default:	goto yy22;
	}
yy64:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
yy65:
	switch (yych) {
	case '\t':
	case ' ':	goto yy64;
	case '\v':
	case '\f':	goto yy39;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy62;
	default:	goto yy20;
	}
yy66:
	++YYCURSOR;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '\t':
	case ' ':	goto yy66;
	case '0':
	case '1':
	case '2':
	case '3':
	case '4':
	case '5':
	case '6':
	case '7':
	case '8':
	case '9':	goto yy62;
	default:	goto yy43;
	}
yy68:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy69;
	default:	goto yy43;
	}
yy69:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy70;
	default:	goto yy43;
	}
yy70:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy71;
	default:	goto yy43;
	}
yy71:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy72;
	default:	goto yy43;
	}
yy72:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy73;
	default:	goto yy43;
	}
yy73:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'V':	goto yy74;
	default:	goto yy43;
	}
yy74:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy75;
	default:	goto yy43;
	}
yy75:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy76;
	default:	goto yy43;
	}
yy76:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'w':	goto yy77;
	default:	goto yy43;
	}
yy77:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_InspectView); }
yy79:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy80;
	default:	goto yy43;
	}
yy80:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy81;
	default:	goto yy43;
	}
yy81:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_Grid); }
yy83:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy84;
	default:	goto yy43;
	}
yy84:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy85;
	default:	goto yy43;
	}
yy85:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy86;
	default:	goto yy43;
	}
yy86:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':	goto yy87;
	default:	goto yy43;
	}
yy87:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy88;
	default:	goto yy43;
	}
yy88:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy89;
	default:	goto yy43;
	}
yy89:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy90;
	default:	goto yy43;
	}
yy90:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_QWordAddr); }
yy92:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy93;
	default:	goto yy43;
	}
yy93:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy94;
	default:	goto yy43;
	}
yy94:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':	goto yy95;
	default:	goto yy43;
	}
yy95:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy96;
	default:	goto yy43;
	}
yy96:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy97;
	default:	goto yy43;
	}
yy97:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy98;
	default:	goto yy43;
	}
yy98:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy99;
	default:	goto yy43;
	}
yy99:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy100;
	default:	goto yy43;
	}
yy100:
	++YYCURSOR;
	{ RETT(RECTTYPE, TYPE_PageMargin); }
yy102:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy103;
	default:	goto yy43;
	}
yy103:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':	goto yy104;
	default:	goto yy43;
	}
yy104:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy105;
	default:	goto yy43;
	}
yy105:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy106;
	default:	goto yy43;
	}
yy106:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_TagAll); }
yy108:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy128;
	default:	goto yy43;
	}
yy109:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy110;
	default:	goto yy43;
	}
yy110:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':	goto yy111;
	case 'O':	goto yy112;
	default:	goto yy43;
	}
yy111:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy121;
	default:	goto yy43;
	}
yy112:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy113;
	default:	goto yy43;
	}
yy113:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':	goto yy114;
	default:	goto yy43;
	}
yy114:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy115;
	default:	goto yy43;
	}
yy115:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy116;
	default:	goto yy43;
	}
yy116:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy117;
	default:	goto yy43;
	}
yy117:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy118;
	default:	goto yy43;
	}
yy118:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy119;
	default:	goto yy43;
	}
yy119:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_MaxOnMemory); }
yy121:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy122;
	default:	goto yy43;
	}
yy122:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':	goto yy123;
	default:	goto yy43;
	}
yy123:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy124;
	default:	goto yy43;
	}
yy124:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'z':	goto yy125;
	default:	goto yy43;
	}
yy125:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy126;
	default:	goto yy43;
	}
yy126:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_MaxMapSize); }
yy128:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy129;
	default:	goto yy43;
	}
yy129:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy130;
	default:	goto yy43;
	}
yy130:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy131;
	default:	goto yy43;
	}
yy131:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':	goto yy132;
	default:	goto yy43;
	}
yy132:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy133;
	default:	goto yy43;
	}
yy133:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy134;
	default:	goto yy43;
	}
yy134:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy135;
	default:	goto yy43;
	}
yy135:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy136;
	default:	goto yy43;
	}
yy136:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy137;
	default:	goto yy43;
	}
yy137:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy138;
	default:	goto yy43;
	}
yy138:
	yych = *++YYCURSOR;
	switch (yych) {
	case '2':	goto yy139;
	default:	goto yy43;
	}
yy139:
	++YYCURSOR;
	{ RETT(INTARRTYPE, TYPE_MemberColumns2); }
yy141:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy142;
	default:	goto yy43;
	}
yy142:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy143;
	default:	goto yy43;
	}
yy143:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':	goto yy144;
	default:	goto yy43;
	}
yy144:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy145;
	default:	goto yy43;
	}
yy145:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy146;
	default:	goto yy43;
	}
yy146:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy147;
	default:	goto yy43;
	}
yy147:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_ReadOnly); }
yy149:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy159;
	default:	goto yy43;
	}
yy150:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy151;
	default:	goto yy43;
	}
yy151:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy152;
	default:	goto yy43;
	}
yy152:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy153;
	default:	goto yy43;
	}
yy153:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy154;
	default:	goto yy43;
	}
yy154:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'M':	goto yy155;
	default:	goto yy43;
	}
yy155:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy156;
	default:	goto yy43;
	}
yy156:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'x':	goto yy157;
	default:	goto yy43;
	}
yy157:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_DetectMax); }
yy159:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy160;
	default:	goto yy43;
	}
yy160:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':	goto yy161;
	case 'P':	goto yy162;
	default:	goto yy43;
	}
yy161:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy167;
	default:	goto yy43;
	}
yy162:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy163;
	default:	goto yy43;
	}
yy163:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy164;
	default:	goto yy43;
	}
yy164:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy165;
	default:	goto yy43;
	}
yy165:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_DumpPage); }
yy167:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy168;
	default:	goto yy43;
	}
yy168:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy169;
	default:	goto yy43;
	}
yy169:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy170;
	default:	goto yy43;
	}
yy170:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy171;
	default:	goto yy43;
	}
yy171:
	++YYCURSOR;
	{ RETT(STRTYPE, TYPE_DumpHeader); }
yy173:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy174;
	default:	goto yy43;
	}
yy174:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy175;
	default:	goto yy43;
	}
yy175:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy176;
	default:	goto yy43;
	}
yy176:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy177;
	default:	goto yy43;
	}
yy177:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy178;
	default:	goto yy43;
	}
yy178:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy179;
	default:	goto yy43;
	}
yy179:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_Language); }
yy181:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy222;
	default:	goto yy43;
	}
yy182:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy214;
	default:	goto yy43;
	}
yy183:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy205;
	default:	goto yy43;
	}
yy184:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy185;
	default:	goto yy43;
	}
yy185:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy186;
	default:	goto yy43;
	}
yy186:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy187;
	default:	goto yy43;
	}
yy187:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':	goto yy190;
	case 'S':	goto yy188;
	case 'V':	goto yy189;
	default:	goto yy43;
	}
yy188:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy199;
	default:	goto yy43;
	}
yy189:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':	goto yy195;
	default:	goto yy43;
	}
yy190:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'P':	goto yy191;
	default:	goto yy43;
	}
yy191:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy192;
	default:	goto yy43;
	}
yy192:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy193;
	default:	goto yy43;
	}
yy193:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_SplitHPos); }
yy195:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy196;
	default:	goto yy43;
	}
yy196:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy197;
	default:	goto yy43;
	}
yy197:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_SplitVPos); }
yy199:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy200;
	default:	goto yy43;
	}
yy200:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy201;
	default:	goto yy43;
	}
yy201:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy202;
	default:	goto yy43;
	}
yy202:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy203;
	default:	goto yy43;
	}
yy203:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_SplitStruct); }
yy205:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy206;
	default:	goto yy43;
	}
yy206:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy207;
	default:	goto yy43;
	}
yy207:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy208;
	default:	goto yy43;
	}
yy208:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'V':	goto yy209;
	default:	goto yy43;
	}
yy209:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy210;
	default:	goto yy43;
	}
yy210:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy211;
	default:	goto yy43;
	}
yy211:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'w':	goto yy212;
	default:	goto yy43;
	}
yy212:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_StructView); }
yy214:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'C':	goto yy215;
	default:	goto yy43;
	}
yy215:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'u':	goto yy216;
	default:	goto yy43;
	}
yy216:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy217;
	default:	goto yy43;
	}
yy217:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy218;
	default:	goto yy43;
	}
yy218:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy219;
	default:	goto yy43;
	}
yy219:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy220;
	default:	goto yy43;
	}
yy220:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_SubCursor); }
yy222:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy223;
	default:	goto yy43;
	}
yy223:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':	goto yy224;
	default:	goto yy43;
	}
yy224:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy225;
	default:	goto yy43;
	}
yy225:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy226;
	default:	goto yy43;
	}
yy226:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy227;
	default:	goto yy43;
	}
yy227:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy228;
	default:	goto yy43;
	}
yy228:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy229;
	default:	goto yy43;
	}
yy229:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_SyncScroll); }
yy231:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy250;
	default:	goto yy43;
	}
yy232:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy233;
	default:	goto yy43;
	}
yy233:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy234;
	default:	goto yy43;
	}
yy234:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'N':	goto yy235;
	case 'S':	goto yy236;
	default:	goto yy43;
	}
yy235:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy246;
	default:	goto yy43;
	}
yy236:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy237;
	case 't':	goto yy238;
	default:	goto yy43;
	}
yy237:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'z':	goto yy243;
	default:	goto yy43;
	}
yy238:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy239;
	default:	goto yy43;
	}
yy239:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy240;
	default:	goto yy43;
	}
yy240:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy241;
	default:	goto yy43;
	}
yy241:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_FontStyle); }
yy243:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy244;
	default:	goto yy43;
	}
yy244:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_FontSize); }
yy246:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy247;
	default:	goto yy43;
	}
yy247:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy248;
	default:	goto yy43;
	}
yy248:
	++YYCURSOR;
	{ RETT(STRTYPE, TYPE_FontName); }
yy250:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy251;
	default:	goto yy43;
	}
yy251:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy252;
	default:	goto yy43;
	}
yy252:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':	goto yy254;
	case 'L':	goto yy256;
	case 'T':	goto yy255;
	case 'W':	goto yy253;
	default:	goto yy43;
	}
yy253:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy272;
	default:	goto yy43;
	}
yy254:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy264;
	default:	goto yy43;
	}
yy255:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy261;
	default:	goto yy43;
	}
yy256:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy257;
	default:	goto yy43;
	}
yy257:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'f':	goto yy258;
	default:	goto yy43;
	}
yy258:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy259;
	default:	goto yy43;
	}
yy259:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_FrameLeft); }
yy261:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy262;
	default:	goto yy43;
	}
yy262:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_FrameTop); }
yy264:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy265;
	default:	goto yy43;
	}
yy265:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy266;
	default:	goto yy43;
	}
yy266:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy267;
	default:	goto yy43;
	}
yy267:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy268;
	default:	goto yy43;
	}
yy268:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '2':	goto yy270;
	default:	goto yy269;
	}
yy269:
	{ RETT(INTTYPE, TYPE_FrameHeight); }
yy270:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_FrameHeight2); }
yy272:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy273;
	default:	goto yy43;
	}
yy273:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy274;
	default:	goto yy43;
	}
yy274:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy275;
	default:	goto yy43;
	}
yy275:
	yych = *++YYCURSOR;
	switch (yych) {
	case '2':	goto yy276;
	default:	goto yy43;
	}
yy276:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_FrameWidth2); }
yy278:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy296;
	default:	goto yy43;
	}
yy279:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy289;
	default:	goto yy43;
	}
yy280:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy281;
	default:	goto yy43;
	}
yy281:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy282;
	default:	goto yy43;
	}
yy282:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'O':	goto yy283;
	default:	goto yy43;
	}
yy283:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy284;
	default:	goto yy43;
	}
yy284:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy285;
	default:	goto yy43;
	}
yy285:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy286;
	default:	goto yy43;
	}
yy286:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy287;
	default:	goto yy43;
	}
yy287:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_ByteOrder); }
yy289:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':	goto yy290;
	default:	goto yy43;
	}
yy290:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy291;
	default:	goto yy43;
	}
yy291:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy292;
	default:	goto yy43;
	}
yy292:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy293;
	default:	goto yy43;
	}
yy293:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy294;
	default:	goto yy43;
	}
yy294:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_BarState); }
yy296:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'A':	goto yy297;
	case 'C':	goto yy298;
	case 'P':	goto yy299;
	case 'W':	goto yy301;
	case 'Z':	goto yy300;
	default:	goto yy43;
	}
yy297:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy327;
	default:	goto yy43;
	}
yy298:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy317;
	default:	goto yy43;
	}
yy299:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy311;
	default:	goto yy43;
	}
yy300:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy307;
	default:	goto yy43;
	}
yy301:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy302;
	default:	goto yy43;
	}
yy302:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy303;
	default:	goto yy43;
	}
yy303:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy304;
	default:	goto yy43;
	}
yy304:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy305;
	default:	goto yy43;
	}
yy305:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_BmpWidth); }
yy307:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy308;
	default:	goto yy43;
	}
yy308:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'm':	goto yy309;
	default:	goto yy43;
	}
yy309:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_BmpZoom); }
yy311:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy312;
	default:	goto yy43;
	}
yy312:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy313;
	default:	goto yy43;
	}
yy313:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy314;
	default:	goto yy43;
	}
yy314:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy315;
	default:	goto yy43;
	}
yy315:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_BmpPallet); }
yy317:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy318;
	default:	goto yy43;
	}
yy318:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy319;
	default:	goto yy43;
	}
yy319:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy320;
	default:	goto yy43;
	}
yy320:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'W':	goto yy321;
	default:	goto yy43;
	}
yy321:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy322;
	default:	goto yy43;
	}
yy322:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy323;
	default:	goto yy43;
	}
yy323:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy324;
	default:	goto yy43;
	}
yy324:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy325;
	default:	goto yy43;
	}
yy325:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_BmpColorWidth); }
yy327:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy328;
	default:	goto yy43;
	}
yy328:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy329;
	default:	goto yy43;
	}
yy329:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy330;
	default:	goto yy43;
	}
yy330:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy331;
	default:	goto yy43;
	}
yy331:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy332;
	default:	goto yy43;
	}
yy332:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'T':	goto yy333;
	default:	goto yy43;
	}
yy333:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy334;
	default:	goto yy43;
	}
yy334:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy335;
	default:	goto yy43;
	}
yy335:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy336;
	default:	goto yy43;
	}
yy336:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy337;
	default:	goto yy43;
	}
yy337:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy338;
	default:	goto yy43;
	}
yy338:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'p':	goto yy339;
	default:	goto yy43;
	}
yy339:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_BmpAddressTooltip); }
yy341:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy352;
	default:	goto yy43;
	}
yy342:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy343;
	default:	goto yy43;
	}
yy343:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy344;
	default:	goto yy43;
	}
yy344:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'D':	goto yy345;
	default:	goto yy43;
	}
yy345:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy346;
	default:	goto yy43;
	}
yy346:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy347;
	default:	goto yy43;
	}
yy347:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy348;
	default:	goto yy43;
	}
yy348:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'c':	goto yy349;
	default:	goto yy43;
	}
yy349:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy350;
	default:	goto yy43;
	}
yy350:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_AutoDetect); }
yy352:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy353;
	default:	goto yy43;
	}
yy353:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'y':	goto yy354;
	default:	goto yy43;
	}
yy354:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'z':	goto yy355;
	default:	goto yy43;
	}
yy355:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy356;
	default:	goto yy43;
	}
yy356:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy357;
	default:	goto yy43;
	}
yy357:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'V':	goto yy358;
	default:	goto yy43;
	}
yy358:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy359;
	default:	goto yy43;
	}
yy359:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy360;
	default:	goto yy43;
	}
yy360:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'w':	goto yy361;
	default:	goto yy43;
	}
yy361:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_AnalyzerView); }
yy363:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy394;
	default:	goto yy43;
	}
yy364:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'l':	goto yy380;
	case 'm':	goto yy379;
	default:	goto yy43;
	}
yy365:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy373;
	default:	goto yy43;
	}
yy366:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy367;
	default:	goto yy43;
	}
yy367:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy368;
	default:	goto yy43;
	}
yy368:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':	goto yy369;
	default:	goto yy43;
	}
yy369:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy370;
	default:	goto yy43;
	}
yy370:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy371;
	default:	goto yy43;
	}
yy371:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_CharSet); }
yy373:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':	goto yy374;
	default:	goto yy43;
	}
yy374:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy375;
	default:	goto yy43;
	}
yy375:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy376;
	default:	goto yy43;
	}
yy376:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'w':	goto yy377;
	default:	goto yy43;
	}
yy377:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_CmdShow); }
yy379:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'b':	goto yy385;
	default:	goto yy43;
	}
yy380:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy381;
	default:	goto yy43;
	}
yy381:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy382;
	default:	goto yy43;
	}
yy382:
	yych = *++YYCURSOR;
	switch (yych) {
	case 's':	goto yy383;
	default:	goto yy43;
	}
yy383:
	++YYCURSOR;
	{ RETT(COLORARRTYPE, TYPE_Colors); }
yy385:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy386;
	default:	goto yy43;
	}
yy386:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'H':	goto yy387;
	default:	goto yy43;
	}
yy387:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy388;
	default:	goto yy43;
	}
yy388:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'i':	goto yy389;
	default:	goto yy43;
	}
yy389:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'g':	goto yy390;
	default:	goto yy43;
	}
yy390:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy391;
	default:	goto yy43;
	}
yy391:
	yych = *++YYCURSOR;
	switch (yych) {
	case 't':	goto yy392;
	default:	goto yy43;
	}
yy392:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_ComboHeight); }
yy394:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy395;
	default:	goto yy43;
	}
yy395:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'r':	goto yy396;
	default:	goto yy43;
	}
yy396:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'U':	goto yy397;
	default:	goto yy43;
	}
yy397:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy398;
	default:	goto yy43;
	}
yy398:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy399;
	default:	goto yy43;
	}
yy399:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy400;
	default:	goto yy43;
	}
yy400:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'R':	goto yy401;
	default:	goto yy43;
	}
yy401:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy402;
	default:	goto yy43;
	}
yy402:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'd':	goto yy403;
	default:	goto yy43;
	}
yy403:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'o':	goto yy404;
	default:	goto yy43;
	}
yy404:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'W':	goto yy405;
	default:	goto yy43;
	}
yy405:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'h':	goto yy406;
	default:	goto yy43;
	}
yy406:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy407;
	default:	goto yy43;
	}
yy407:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'n':	goto yy408;
	default:	goto yy43;
	}
yy408:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'S':	goto yy409;
	default:	goto yy43;
	}
yy409:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'a':	goto yy410;
	default:	goto yy43;
	}
yy410:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'v':	goto yy411;
	default:	goto yy43;
	}
yy411:
	yych = *++YYCURSOR;
	switch (yych) {
	case 'e':	goto yy412;
	default:	goto yy43;
	}
yy412:
	++YYCURSOR;
	{ RETT(INTTYPE, TYPE_ClearUndoRedoWhenSave); }
yy414:
	++YYCURSOR;
	{ goto comment2; }
yy416:
	++YYCURSOR;
	{ goto comment; }
}


comment:

{
	YYCTYPE yych;
	if ((YYLIMIT - YYCURSOR) < 2) if(!fill(2)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy422;
	case '*':	goto yy420;
	default:	goto yy424;
	}
yy420:
	++YYCURSOR;
	switch ((yych = *YYCURSOR)) {
	case '/':	goto yy425;
	default:	goto yy421;
	}
yy421:
	{ if(cursor == s->eof)RET(0); goto comment; }
yy422:
	++YYCURSOR;
	{ if(cursor == s->eof) RET(0); s->tok = s->pos = cursor; s->line++; goto comment; }
yy424:
	yych = *++YYCURSOR;
	goto yy421;
yy425:
	++YYCURSOR;
	{ if(cursor == s->eof || cursor+1 == s->eof)RET(0); goto std; }
}

comment2:

{
	YYCTYPE yych;
	if (YYLIMIT <= YYCURSOR) if(!fill(1)) { return 0; }
	yych = *YYCURSOR;
	switch (yych) {
	case '\n':	goto yy429;
	default:	goto yy431;
	}
yy429:
	++YYCURSOR;
	{ if(cursor == s->eof) RET(0); s->tok = s->pos = cursor; s->line++; goto std; }
yy431:
	++YYCURSOR;
	{ if(cursor == s->eof)RET(0); goto comment2; }
}

}