//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BZres_us.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_BZINSPECTVIEW               103
#define IDC_BMPPOINTER                  104
#define IDD_BZANALYZERVIEW              105
#define IDD_PROGRESSDIALOG              106
#define IDR_MAINFRAME                   128
#define IDR_BZTYPE                      129
#define IDP_OLE_INIT_FAILED             129
#define IDD_DIALOG1                     137
#define IDD_SETUP_COLOR                 138
#define IDR_BMPVIEW                     141
#define IDD_SETTING                     143
#define IDD_INPUT                       144
#define IDR_MENU_POPUP                  145
#define IDC_LIST_TAG                    1000
#define IDC_LIST_MEMBER                 1001
#define IDAPPLY                         1002
#define IDC_PARTSLIST                   1008
#define IDC_TEXTCOLOR                   1009
#define IDC_BACKCOLOR                   1010
#define IDC_SAMPLE                      1011
#define IDC_STATIC_MEMBER               1012
#define IDE_MAXONMEMORY                 1014
#define IDB_TAGALL                      1014
#define IDE_MAXMAPSIZE                  1015
#define IDC_QWORDADDR                   1016
#define IDE_DUMPPAGE                    1017
#define IDE_VALUE                       1018
#define IDB_RESET                       1019
#define IDC_INS_UNSIGNED                1021
#define IDC_INS_SIGNED                  1021
#define IDC_INS_INTEL                   1022
#define IDE_INS_HEX                     1023
#define IDE_INS_BINARY1                 1024
#define IDE_INS_BINARY2                 1025
#define IDC_INS_STATIC1                 1026
#define IDE_INS_BINARY4                 1027
#define IDE_INS_BINARY8                 1028
#define IDE_INS_FLOAT                   1029
#define IDE_INS_DOUBLE                  1030
#define IDC_INS_STATIC2                 1031
#define IDC_INS_STATIC4                 1032
#define IDC_INS_STATIC8                 1033
#define IDC_INS_STATICF                 1034
#define IDC_INS_STATICD                 1035
#define IDB_ANALYZE_START               1036
#define IDE_INS_8BITS                   1037
#define IDC_ANALYZE_TYPE                1037
#define IDL_ANALYZE_RESULT              1038
#define IDP_ANALYZE_PERCENT             1039
#define IDB_ANALYZER_SAVE               1041
#define IDB_ANALYZER_SAVEALL            1042
#define IDC_COMBO_TOOLBAR               1043
#define IDC_CLEARUNDOREDOWHENSAVE       1044
#define IDB_RESETSETTINGS               1045
#define IDS_COLOR_ADDRESS               3000
#define IDS_COLOR_ADDRESS2              3001
#define IDS_COLOR_TEXT                  3002
#define IDS_COLOR_SELECT                3003
#define IDS_COLOR_MARK                  3004
#define IDS_COLOR_MISMATCH              3005
#define IDS_COLOR_STRUCT                3006
#define IDS_COLOR_MEMBER                3007
#define IDS_COLOR_OVERBROTHER           3008
#define IDS_COLOR_HORIZON               3009
#define IDS_COLOR_ADDRESS3              3010
#define IDS_ERR_FILENOTFOUND            4000
#define IDS_ERR_SYNTAX                  4001
#define IDS_ERR_MALLOC                  4002
#define IDS_ERR_READFILE                4003
#define IDT_FINDBOX                     5000
#define ID_CHAR_ASCII                   32770
#define ID_CHAR_SJIS                    32771
#define ID_CHAR_UNICODE                 32772
#define ID_CHAR_JIS                     32773
#define ID_CHAR_EUC                     32774
#define ID_CHAR_UTF8                    32775
#define ID_CHAR_EBCDIC                  32776
#define ID_CHAR_EPWING                  32777
#define ID_CHAR_LAST                    32777
#define ID_CHAR_AUTODETECT              32779
#define ID_EDIT_VALUE                   32780
#define ID_EDIT_READONLY                32781
#define ID_EDIT_READONLYOPEN            32782
#define ID_BYTEORDER_INTEL              32783
#define ID_BYTEORDER_68K                32784
#define ID_VIEW_BITMAP                  32790
#define ID_VIEW_STRUCT                  32791
#define ID_VIEW_INSPECT                 32792
#define ID_VIEW_SPLIT_H                 32794
#define ID_VIEW_SPLIT_V                 32795
#define ID_VIEW_FONT                    32800
#define ID_VIEW_COLOR                   32801
#define ID_VIEW_FULLPATH                32802
#define ID_VIEW_SUBCURSOR               32803
#define ID_JUMP_FIND                    32810
#define ID_JUMP_FINDNEXT                32811
#define ID_JUMP_COMPARE                 32812
#define ID_JUMP_TO                      32813
#define ID_JUMP_OFFSET                  32814
#define ID_JUMP_RETURN                  32815
#define ID_JUMP_MARK                    32816
#define ID_JUMP_MARKNEXT                32817
#define ID_JUMP_START                   32818
#define ID_JUMP_END                     32819
#define ID_HELP_CONTENS                 32830
#define ID_LANG_JPN                     32831
#define ID_LANG_ENU                     32832
#define ID_TOOLS_EDITDEF                32833
#define ID_BMPVIEW_WIDTH128             32836
#define ID_BMPVIEW_WIDTH256             32837
#define ID_BMPVIEW_ZOOM                 32838
#define ID_TOOLS_SETTING                32839
#define ID_FILE_SAVE_DUMPLIST           32841
#define ID_EDIT_COPY_DUMP               32842
#define ID_JUMP_BASE                    32844
#define ID_VIEW_SYNCSCROLL              32847
#define ID_Menu                         32848
#define ID_VIEW_GRID1                   32849
#define ID_BMPVIEW_8BITCOLOR            32850
#define ID_BMPVIEW_24BITCOLOR           32851
#define ID_BMPVIEW_32BITCOLOR           32852
#define ID_BMPVIEW_ADDRESSTOOLTIP       32853
#define ID_BMPVIEW_PALETTE_BZ           32854
#define ID_BMPVIEW_PALETTE_SAFETY       32855
#define ID_VIEW_ANALYZER                32858
#define ID_BMP                          32859
#define ID_INDICATOR_INFO               0xE710
#define ID_INDICATOR_SIZE               0xE711
#define ID_INDICATOR_CHAR               0xE712
#define ID_INDICATOR_INS                0xE713
#define IDS_AUTOCOLOR                   61447
#define IDS_OTHERCOLOR                  61448
#define IDS_EDIT_OVR                    61470
#define IDS_EDIT_INS                    61471
#define IDS_CHANGE_LANGUAGE             61500
#define IDS_COMPARE_OK                  61501
#define IDS_ALLFILTER                   61502
#define IDS_ERR_RANGE                   61514
#define IDS_ERR_READONLY                61515
#define IDS_ERR_FINDSTRING              61516
#define IDS_ERR_MAP_RO                  61517
#define IDS_ERR_OVER4G                  61518
#define IDS_ERR_COPY                    61519
#define IDS_SAVEDUMP_CAPTION            61520
#define IDS_EBCDIC_FILE                 61521
#define IDS_STRUCT_FILE                 61522
#define IDS_EDIT_RO                     61524

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        146
#define _APS_NEXT_COMMAND_VALUE         32860
#define _APS_NEXT_CONTROL_VALUE         1046
#define _APS_NEXT_SYMED_VALUE           107
#endif
#endif
